[package]
name = "broadcast-frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
yew = { workspace = true }
wasm-bindgen = { workspace = true }
gloo-net = { workspace = true }
gloo-timers = { workspace = true, features = ["futures"] }
gloo-file = { workspace = true, features = ["futures"] }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = [
    "MediaQueryList",
    "MediaQueryListEvent",
    "Window",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "KeyboardEvent",
    "Navigator",
    "Clipboard",
    "DragEvent",
    "DataTransfer",
    "FileList",
    "File",
] }
serde = { workspace = true }
serde_json = { workspace = true }
bitcoin = { workspace = true }
base64 = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
zip = { workspace = true }
tx-core = { path = "../tx-core" }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
